[package]
name = "test-playbook"
version = "0.1.0"
authors = ["Nicolas KÃ¼chler <nico.kuechler@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
